### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by xnanodax** [NJCA88/dotify#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
+ Great work overall on the proposal :) Let's create wiki pages on the [wiki tab](https://github.com/NJCA88/dotify/wiki).
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
+ Let's specify on the MVP 3 to users can play songs and create a playlist CRUD cycle. (users wont upload songs but they will create, read, update, delete play list of pre-existing songs).
+ Lets also swap MVP 5 and MVP 6. Let's get continuous player before search! 

---

# Database Schema

- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [x] not null
    - [x] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
+ Format your table to look like [this](https://github.com/appacademy/bluebird/wiki)
+ For the album covers and song files, we will "save" these as associations that will be connected to AWS. You wont need a column for the actual music file.
+ Consider adding an email column to the users. It makes the page look more official + spotify does this!

---

# Sample State

- [x] State shape is flat!
- [ ] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
+ Did you mean playlist number 11? playlist: { 15: { id: 11 } }
+ You probably want to also include your album AND users slice of state under entities since you have keys referencing those objects.
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by xnanodax** [comment]
Hey Chris :) Overall, great start into your proposal! 
I've only looked over everything but routes. 

Please format your docs to look like the wiki pages from [blue bird](https://github.com/appacademy/bluebird/wiki) and then i'll be able to look over your routes!

**Comment by NJCA88** [comment]
Formatting for routes  / MVP list is done, so routes should be ready for review. Made the recommended switch to MVP.  Will finish this up right after A06.  Would do now but my train is about to arrive in SF!

**Comment by xnanodax** [comment]
For the Schema, for Spotify, albums have genres. Not songs! We can add the genre_id to the `Album` tables and remove it from the `Song` tables.
