### ISSUE TITLE
PA revier: User Auth

### ISSUE THREAD

**Issue by NJCA88** [NJCA88/dotify#2]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
 - [x] Styling is complete and similar to spotify web player
- [x] bug free navigation
   - [ ] renders errors / clears errors at appropriate times (incomplete)
   - [x] cannot access protected routes when not logged in
   - [x] cannot access splash / login / signup when already logged in
-  [x] demo login works

**Comment by xnanodax** [comment]
Great job Chris :)

Currently on heroku, when I click on the demo login from the `https://chrisatwooddotify.herokuapp.com/?#/signup` page, it redirects me back to splash!
