### ISSUE TITLE
Continuous Play

### ISSUE THREAD

**Issue by NJCA88** [NJCA88/dotify#4]
- [x] Songs will begin playing when you hit play
  - [x] Functions from both the player component at the bottom, and hitting play on the track name
- [x] Songs will not stop when you navigate away from the album you were looking at
- [x] Songs will auto move to next song on end of previous song
- [x] Can skip to next song
- [x] Can skip to previous song.

**Comment by xnanodax** [comment]
Go ahead and check off the parts you have finished!
